(()=>{
const norm=s=>(s??'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
const num=v=>{const m=(v??'').toString().replace(',','.').match(/[-+]?\d+(?:\.\d+)?/);return m?Number(m[0]):null};
const keysOf=o=>o&&typeof o==='object'?Object.keys(o):[];
const pick=(o,names)=>{if(!o||typeof o!=='object')return undefined;for(const k of Object.keys(o)){const nk=norm(k).replace(/[^a-z0-9%]/g,'');if(names.some(n=>nk===n||nk.includes(n)))return o[k]}return undefined};
function walk(v,out,depth=0){if(depth>8||v==null)return;if(Array.isArray(v)){for(const x of v)walk(x,out,depth+1);return}if(typeof v==='object'){out.push(v);for(const x of Object.values(v))walk(x,out,depth+1)}}
function storageObjects(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);try{const v=JSON.parse(localStorage.getItem(k));walk(v,out)}catch{}}return out}
function lineName(o){return pick(o,['linea','linename','nombrelinea','line','studyline','estudio','strategy','estrategia'])}
function histHit(o){return pick(o,['historicalhitrate','historicalhit','hithistorico','aciertohistorico','porcentajehistorico','percenthistorico','histacierto','hitratehist','historicalpercent','pcthistorico'])}
function histRoi(o){return pick(o,['historicalroi','roihistorico','histroi','roihist'])}
function currentHit(o){return pick(o,['currenthitrate','currenthit','aciertoactual','porcentajeactual','percentactual','pctactual'])}
function currentRoi(o){return pick(o,['currentroi','roiactual'])}
function idVal(o){return pick(o,['lineid','idlinea','strategyid','studyid'])}
function textOf(o){try{return norm(JSON.stringify(o))}catch{return''}}
function catalog(){const objs=storageObjects(),map=new Map(),byId=new Map();for(const o of objs){const ln=lineName(o);if(!ln)continue;const name=String(ln).trim();if(!name||name.length>180)continue;const h=histHit(o),r=histRoi(o),id=idVal(o);const rec={name,histHit:h,histRoi:r,currentHit:currentHit(o),currentRoi:currentRoi(o),raw:o};const k=norm(name);const prev=map.get(k)||{};map.set(k,{...prev,...rec,histHit:h??prev.histHit,histRoi:r??prev.histRoi,currentHit:rec.currentHit??prev.currentHit,currentRoi:rec.currentRoi??prev.currentRoi});if(id!=null)byId.set(String(id),map.get(k))}
 for(const table of document.querySelectorAll('table')){const hs=[...table.querySelectorAll('thead th')].map(x=>norm(x.textContent));const li=hs.findIndex(h=>h.includes('linea'));const hi=hs.findIndex(h=>h.includes('histor')&&h.includes('%')||h.includes('acierto histor'));const ri=hs.findIndex(h=>h.includes('roi')&&h.includes('histor'));if(li<0)continue;for(const r of table.querySelectorAll('tbody tr')){const c=[...r.cells],name=c[li]?.textContent?.trim();if(!name)continue;const k=norm(name),prev=map.get(k)||{};map.set(k,{...prev,name,histHit:hi>=0?c[hi]?.textContent:prev.histHit,histRoi:ri>=0?c[ri]?.textContent:prev.histRoi})}}
 return {map,byId,objs}}
function rowHeaders(table){return [...table.querySelectorAll('thead th')].map(h=>norm(h.textContent))}
function ensureCols(table){if(!table.tHead?.rows[0])return null;const wanted=[['linea','Línea'],['% historico','% histórico'],['roi historico','ROI histórico'],['% actual','% actual'],['roi actual','ROI actual']];let hs=rowHeaders(table);for(const [k,label] of wanted){if(!hs.some(h=>h.includes(k))){const th=document.createElement('th');th.textContent=label;table.tHead.rows[0].appendChild(th);hs=rowHeaders(table)}}return hs}
function alertTables(){return [...document.querySelectorAll('table')].filter(t=>{const txt=norm(t.parentElement?.textContent);return txt.includes('aviso')||txt.includes('pronostico')||txt.includes('pick')})}
function scoreCandidate(alertText,rec){const rt=textOf(rec.raw),name=norm(rec.name);let s=0;const meaningful=alertText.split(/[^a-z0-9]+/).filter(x=>x.length>=4);for(const tok of meaningful)if(rt.includes(tok)||name.includes(tok))s+=1;const market=pick(rec.raw,['apuesta','mercado','market','bet']);if(market&&alertText.includes(norm(market)))s+=5;const comp=pick(rec.raw,['liga','competicion','competition','league']);if(comp&&alertText.includes(norm(comp)))s+=4;return s}
function resolveFromStorage(rowText,cat){const objs=cat.objs;let direct=[];for(const o of objs){const ot=textOf(o);if(!ot)continue;const tokens=rowText.split(/[^a-z0-9]+/).filter(x=>x.length>=5);const matched=tokens.filter(t=>ot.includes(t)).length;if(matched<2)continue;const ln=lineName(o),lid=idVal(o);if(ln||lid!=null)direct.push({o,matched})}
 direct.sort((a,b)=>b.matched-a.matched);for(const d of direct){const ln=lineName(d.o);if(ln&&cat.map.has(norm(ln)))return cat.map.get(norm(ln));const lid=idVal(d.o);if(lid!=null&&cat.byId.has(String(lid)))return cat.byId.get(String(lid));if(ln)return {name:String(ln),raw:d.o,histHit:histHit(d.o),histRoi:histRoi(d.o),currentHit:currentHit(d.o),currentRoi:currentRoi(d.o)}}
 let best=null,bestScore=0;for(const rec of cat.map.values()){const s=scoreCandidate(rowText,rec);if(s>bestScore){bestScore=s;best=rec}}return bestScore>=6?best:null}
function currentStatsByLine(){const out=new Map();const tables=[...document.querySelectorAll('table')].filter(t=>norm(t.parentElement?.textContent).includes('resuelt'));for(const t of tables){const hs=rowHeaders(t),li=hs.findIndex(h=>h.includes('linea')),ri=hs.findIndex(h=>h==='resultado'||h.includes('resultado')),pi=hs.findIndex(h=>h.includes('beneficio')),si=hs.findIndex(h=>h.includes('stake'));if(li<0)continue;for(const r of t.querySelectorAll('tbody tr')){if(r.classList.contains('af-muted'))continue;const c=[...r.cells],name=c[li]?.textContent?.trim();if(!name)continue;const k=norm(name),s=out.get(k)||{n:0,w:0,profit:0,stake:0};s.n++;const txt=norm(ri>=0?c[ri]?.textContent:r.textContent);if(/ganad|acert|win|verde/.test(txt))s.w++;if(pi>=0)s.profit+=num(c[pi]?.textContent)||0;s.stake+=si>=0?(num(c[si]?.textContent)||1):1;out.set(k,s)}}return out}
function fill(){const cat=catalog(),stats=currentStatsByLine();for(const table of alertTables()){let hs=ensureCols(table);if(!hs)continue;hs=rowHeaders(table);const idx={line:hs.findIndex(h=>h==='linea'||h.includes('línea')),hh:hs.findIndex(h=>h.includes('% histor')),hr:hs.findIndex(h=>h.includes('roi histor')),ch:hs.findIndex(h=>h.includes('% actual')),cr:hs.findIndex(h=>h.includes('roi actual'))};for(const r of table.querySelectorAll('tbody tr')){while(r.cells.length<hs.length)r.insertCell();const cells=[...r.cells];let rec=null;const existing=idx.line>=0?cells[idx.line]?.textContent?.trim():'';if(existing)rec=cat.map.get(norm(existing))||null;const baseText=norm([...cells].filter((_,i)=>![idx.line,idx.hh,idx.hr,idx.ch,idx.cr].includes(i)).map(c=>c.textContent).join(' '));if(!rec)rec=resolveFromStorage(baseText,cat);if(!rec)continue;if(idx.line>=0&&!cells[idx.line].textContent.trim())cells[idx.line].textContent=rec.name||'';if(idx.hh>=0&&!cells[idx.hh].textContent.trim()&&rec.histHit!=null)cells[idx.hh].textContent=String(rec.histHit).includes('%')?String(rec.histHit):String(rec.histHit)+'%';if(idx.hr>=0&&!cells[idx.hr].textContent.trim()&&rec.histRoi!=null)cells[idx.hr].textContent=String(rec.histRoi).includes('%')?String(rec.histRoi):String(rec.histRoi)+'%';const s=stats.get(norm(rec.name));const ch=s?(s.n?100*s.w/s.n:0):(num(rec.currentHit));const cr=s?(s.stake?100*s.profit/s.stake:0):(num(rec.currentRoi));if(idx.ch>=0&&ch!=null)cells[idx.ch].textContent=Number(ch).toFixed(2)+'%';if(idx.cr>=0&&cr!=null)cells[idx.cr].textContent=Number(cr).toFixed(2)+'%'}}}}
let timer;const run=()=>{clearTimeout(timer);timer=setTimeout(fill,80)};new MutationObserver(run).observe(document.documentElement,{subtree:true,childList:true,characterData:true});setTimeout(fill,400);setTimeout(fill,1400);window.appFutbolVerifyAssociations=()=>{fill();const rows=[];for(const t of alertTables()){const hs=rowHeaders(t),li=hs.findIndex(h=>h.includes('linea')),hi=hs.findIndex(h=>h.includes('% histor')),ri=hs.findIndex(h=>h.includes('roi histor'));for(const r of t.querySelectorAll('tbody tr'))rows.push({linea:li>=0?r.cells[li]?.textContent.trim():'',historico:hi>=0?r.cells[hi]?.textContent.trim():'',roiHistorico:ri>=0?r.cells[ri]?.textContent.trim():''})}return rows};
})();