(()=>{
'use strict';
const GENERATED='appFutbolGeneratedAlertsV2';
const LIVE='appFutbolLiveMatchesV1';
const RUN_TIMEOUT=15000;
const norm=s=>(s??'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
const n=v=>{const m=String(v??'').replace(',','.').match(/[-+]?\d+(?:\.\d+)?/);return m?Number(m[0]):null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const headers=t=>[...t.querySelectorAll('thead th')].map(x=>norm(x.textContent));
const fmt=v=>v==null||v===''?'Pendiente':(Number.isFinite(n(v))?n(v).toFixed(2)+'%':String(v));
let generated=[];try{generated=JSON.parse(localStorage.getItem(GENERATED)||'[]')}catch{}
function save(){localStorage.setItem(GENERATED,JSON.stringify(generated))}
function toast(msg){document.querySelectorAll('[data-af-engine-toast]').forEach(x=>x.remove());const d=document.createElement('div');d.dataset.afEngineToast='1';d.textContent=msg;d.style.cssText='position:fixed;right:14px;bottom:14px;z-index:999999;background:#111827;color:white;padding:12px 16px;border-radius:10px;box-shadow:0 8px 30px #0003;max-width:540px';document.body.appendChild(d);setTimeout(()=>d.remove(),7000)}
function domLines(){const out=[];for(const t of document.querySelectorAll('table')){const hs=headers(t);const li=hs.findIndex(h=>h==='linea'||h==='línea'||h.includes('linea')||h.includes('línea'));if(li<0)continue;const hi=hs.findIndex(h=>h.includes('% hist')||h.includes('acierto hist'));const ri=hs.findIndex(h=>h.includes('roi hist')||(h==='roi'));const si=hs.findIndex(h=>h.includes('stake'));const ai=hs.findIndex(h=>h.includes('activo')||h.includes('estado'));const ci=hs.findIndex(h=>h.includes('cuota')||h.includes('rango'));const ligi=hs.findIndex(h=>h.includes('liga')||h.includes('compet'));for(const r of t.querySelectorAll('tbody tr')){const name=r.cells[li]?.textContent.trim();if(!name||/manual\s*\/\s*sin\s*linea/i.test(name))continue;const st=ai>=0?norm(r.cells[ai]?.textContent):'';if(/desactiv|inactiv|no activar|descart|false/.test(st))continue;let min=null,max=null;if(ci>=0){const nums=(r.cells[ci]?.textContent||'').replace(',','.').match(/\d+(?:\.\d+)?/g)||[];if(nums.length){min=+nums[0];max=nums.length>1?+nums[1]:null}}out.push({name,histHit:hi>=0?n(r.cells[hi]?.textContent):null,histRoi:ri>=0?n(r.cells[ri]?.textContent):null,stake:si>=0?r.cells[si]?.textContent.trim()||null:null,league:ligi>=0?r.cells[ligi]?.textContent.trim()||'':'',min,max});}}
const map=new Map();for(const l of out){const k=norm(l.name);if(!map.has(k)||((map.get(k).histHit==null)&&(l.histHit!=null)))map.set(k,l)}return [...map.values()];}
function storageLines(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);let v;try{v=JSON.parse(localStorage.getItem(k))}catch{continue}const walk=(x,d=0)=>{if(d>7||x==null)return;if(Array.isArray(x)){x.forEach(y=>walk(y,d+1));return}if(typeof x!=='object')return;const name=x.linea||x.line||x.nombreLinea||x.estudio||x.strategy; if(typeof name==='string'&&name.trim()&&!/manual\s*\/\s*sin\s*linea/i.test(name)){const active=!(/desactiv|inactiv|no activar|descart/.test(norm(x.estado||x.status||''))||x.active===false||x.enabled===false);if(active)out.push({name:name.trim(),histHit:n(x.historicalHitRate??x.aciertoHistorico??x.porcentajeHistorico),histRoi:n(x.historicalROI??x.roiHistorico),stake:x.stake??null,league:x.liga||x.competicion||'',min:n(x.minOdds??x.cuotaMinima),max:n(x.maxOdds??x.cuotaMaxima)});}Object.values(x).forEach(y=>walk(y,d+1));};walk(v)}return out}
function allLines(){const m=new Map();for(const l of [...domLines(),...storageLines()]){const k=norm(l.name);if(!k)continue;const p=m.get(k);if(!p)m.set(k,l);else m.set(k,{...p,...l,histHit:l.histHit??p.histHit,histRoi:l.histRoi??p.histRoi,stake:l.stake??p.stake});}return [...m.values()]}
function parseRule(line){const t=norm(line.name);let home5=null,away5=null,home3=null,away3=null;let m=t.match(/(?:^|\D)(\d{1,2})\s*v(?:s)?\s*(\d{1,2})(?:\D|$)/);if(m){if(/h3|3 casa|3 fuera|3 partidos/.test(t)){home3=+m[1];away3=+m[2]}else{home5=+m[1];away5=+m[2]}}
let market='';if(/under\s*2[,.]5|u2[,.]5/.test(t))market='Under 2.5';else if(/over\s*2[,.]5|o2[,.]5/.test(t))market='Over 2.5';else if(/empate|\bdraw\b/.test(t))market='Empate';else if(/visitante|\baway\b|\bvisitor\b/.test(t))market='Visitante';else if(/\blocal\b|\bhome\b/.test(t))market='Local';
const strongWeak=/buena forma|7\s*\+|>=\s*7|7 o mas/.test(t)&&/debil|4\s*-|<=\s*4|4 o menos/.test(t);return {home5,away5,home3,away3,market,strongWeak,text:t};}
function leagueCompatible(line,match){if(!line.league)return true;const a=norm(line.league),b=norm(match.league);return !a||!b||a.includes(b)||b.includes(a)||a.includes('22 ligas')||a.includes('big five')}
function matches(line,m){if(!leagueCompatible(line,m))return false;const r=parseRule(line);if(r.home5!=null&&(m.homePts!==r.home5||m.awayPts!==r.away5))return false;if(r.home3!=null&&(m.homePts3!==r.home3||m.awayPts3!==r.away3))return false;if(r.strongWeak&&!(m.homePts>=7&&m.awayPts<=4))return false;if(r.home5==null&&r.home3==null&&!r.strongWeak)return false;return true}
function dedupId(a){return norm([a.date,a.home,a.away,a.bet,a.line].join('|'))}
function existing(a){const id=dedupId(a);if(generated.some(x=>dedupId(x)===id))return true;for(const t of document.querySelectorAll('table'))for(const r of t.querySelectorAll('tbody tr')){const s=norm(r.textContent);if(s.includes(norm(a.home))&&s.includes(norm(a.away))&&s.includes(norm(a.line)))return true}return false}
function host(){const h=[...document.querySelectorAll('h1,h2,h3')].find(x=>norm(x.textContent).includes('avisos pendientes'));return h?.parentElement||document.body}
function render(){let box=document.querySelector('[data-af-real-alerts]');if(!generated.length){box?.remove();return}if(!box){box=document.createElement('section');box.dataset.afRealAlerts='1';box.style.cssText='margin:16px 18px;padding:14px;border:1px solid #d1d5db;border-radius:14px;background:#fff;overflow:auto';host().appendChild(box)}box.innerHTML='<h3 style="margin:0 0 10px">Avisos detectados automáticamente</h3><table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr><th>Fecha</th><th>Liga</th><th>Partido</th><th>Pronóstico</th><th>Línea</th><th>% hist.</th><th>ROI hist.</th><th>Stake</th><th></th></tr></thead><tbody>'+generated.map((a,i)=>`<tr><td>${esc(a.date)}</td><td>${esc(a.league)}</td><td>${esc(a.home)} - ${esc(a.away)}</td><td>${esc(a.bet)}</td><td>${esc(a.line)}</td><td>${fmt(a.histHit)}</td><td>${fmt(a.histRoi)}</td><td>${esc(a.stake??'Pendiente')}</td><td><button data-af-del-real="${i}" style="background:#b91c1c;color:#fff;border:0;border-radius:7px;padding:5px 8px">Eliminar</button></td></tr>`).join('')+'</tbody></table>';box.querySelectorAll('[data-af-del-real]').forEach(b=>b.onclick=()=>{generated.splice(+b.dataset.afDelReal,1);save();render()})}
async function refreshLive(){if(typeof window.appFutbolRefreshLiveMatches!=='function')throw new Error('La fuente de partidos no está cargada');const s=await Promise.race([window.appFutbolRefreshLiveMatches(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Tiempo máximo de carga superado')),RUN_TIMEOUT))]);let arr=[];try{arr=JSON.parse(localStorage.getItem(LIVE)||'[]')}catch{}return {arr,status:s}}
function syncComo(){for(const t of document.querySelectorAll('table')){const hs=headers(t);const pi=hs.findIndex(h=>h.includes('partido'));const li=hs.findIndex(h=>h==='linea(s)'||h==='linea'||h==='línea'||h.includes('linea'));if(pi<0||li<0)continue;for(const r of t.querySelectorAll('tbody tr')){const p=norm(r.cells[pi]?.textContent);if(p.includes('como')&&p.includes('leipzig')&&/manual|sin linea/.test(norm(r.cells[li]?.textContent)))r.cells[li].textContent='Favorito local Champions 1,70–1,84';}}
for(const t of document.querySelectorAll('table')){const hs=headers(t);const li=hs.findIndex(h=>h==='linea'||h==='línea'||h.includes('linea'));if(li<0)continue;for(const r of t.querySelectorAll('tbody tr'))if(/manual\s*\/\s*sin\s*linea/.test(norm(r.cells[li]?.textContent))&&norm(r.textContent).includes('como')&&norm(r.textContent).includes('leipzig'))r.cells[li].textContent='Favorito local Champions 1,70–1,84';}}
async function run(){const b=[...document.querySelectorAll('[data-af-run-now]')];b.forEach(x=>{x.disabled=true;x.textContent='Analizando…'});const watchdog=setTimeout(()=>b.forEach(x=>{x.disabled=false;x.textContent='Ejecutar ahora'}),RUN_TIMEOUT+2000);try{syncComo();const {arr,status}=await refreshLive();const lines=allLines();let candidates=0,added=0;for(const m of arr){for(const l of lines){if(!matches(l,m))continue;candidates++;const rule=parseRule(l);const a={date:m.date,league:m.league,home:m.home,away:m.away,bet:rule.market||'Revisar mercado',line:l.name,histHit:l.histHit,histRoi:l.histRoi,stake:l.stake,detectedAt:new Date().toISOString()};if(existing(a))continue;generated.push(a);added++;}}const mm=new Map();for(const a of generated)mm.set(dedupId(a),a);generated=[...mm.values()];save();render();syncComo();window.appFutbolVerifyAssociations?.();toast(`Análisis completado: ${added} nuevos · ${arr.length} partidos próximos · ${lines.length} líneas activas · ${candidates} coincidencias · ${status.loaded} ligas cargadas${status.failed?` · ${status.failed} con error`:''}.`);return {added,matches:arr.length,lines:lines.length,candidates,loaded:status.loaded,failed:status.failed}}catch(e){console.error(e);toast('ERROR DE AUTOMATIZACIÓN: '+(e?.message||e));return {error:String(e)}}finally{clearTimeout(watchdog);b.forEach(x=>{x.disabled=false;x.textContent='Ejecutar ahora'})}}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-af-run-now]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();run()},true);
new MutationObserver(()=>{render();syncComo()}).observe(document.documentElement,{subtree:true,childList:true});setTimeout(()=>{render();syncComo()},500);window.appFutbolAutomation={run,renderGenerated:render,syncComo};window.appFutbolRunNow=run;
})();