(()=>{
const KEY='appFutbolEnhancementsV4';
const state=JSON.parse(localStorage.getItem(KEY)||'{"disabledResolved":{},"deletedResolved":{},"bookmakers":[],"sort":{"field":"roi","dir":"desc"}}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
const num=s=>{const m=(s||'').replace(',','.').match(/[-+]?\d+(?:\.\d+)?/);return m?Number(m[0]):0};
const hash=s=>{let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))|0;return String(h)};
const visible=e=>!!(e&&e.getClientRects&&e.getClientRects().length);
const css=`.af-red{background:#fee2e2!important;border-color:#ef4444!important;color:#991b1b!important}.af-green{background:#dcfce7!important;border-color:#22c55e!important;color:#166534!important}.af-muted{opacity:.45!important;filter:grayscale(.4)}.af-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.af-btn{border:0;border-radius:10px;padding:9px 12px;font-weight:700;cursor:pointer;background:#111827;color:white}.af-btn.secondary{background:#e5e7eb;color:#111827}.af-btn.danger{background:#b91c1c}.af-badge{display:inline-block;padding:3px 7px;border-radius:999px;font-size:12px;font-weight:700;background:#eef2ff;color:#3730a3;margin-left:6px}.af-toast{position:fixed;right:14px;bottom:14px;z-index:99999;background:#111827;color:white;padding:12px 16px;border-radius:10px;box-shadow:0 8px 30px #0003;max-width:420px}.af-actions{display:flex;gap:6px;flex-wrap:wrap}.af-sort{cursor:pointer;user-select:none}.af-sort:after{content:' ↕';opacity:.5}.af-note{font-size:12px;opacity:.7}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function toast(msg){const d=document.createElement('div');d.className='af-toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),4500)}
function activeViewWord(word){return [...document.querySelectorAll('[aria-selected="true"],.active,.selected,h1,h2,h3,[role="tab"]')].some(e=>visible(e)&&norm(e.textContent).includes(word));}
function tableHeaders(t){return [...t.querySelectorAll('thead th')].map(x=>norm(x.textContent));}
function scoreResolvedTable(t){const h=tableHeaders(t).join(' '),p=norm(t.parentElement?.textContent);let s=0;if(/resultado|result/.test(h))s+=4;if(/cuota|odds/.test(h))s+=2;if(/stake|beneficio|profit/.test(h))s+=2;if(/fecha|partido|match/.test(h))s+=2;if(p.includes('resuelt'))s+=5;return s;}
function resolvedTable(){const all=[...document.querySelectorAll('table')].filter(visible);const ranked=all.map(t=>[t,scoreResolvedTable(t)]).sort((a,b)=>b[1]-a[1]);return ranked[0]?.[1]>=4?ranked[0][0]:null;}
function alertTables(){return [...document.querySelectorAll('table')].filter(t=>{if(!visible(t))return false;const h=tableHeaders(t).join(' '),p=norm(t.parentElement?.textContent);return p.includes('aviso')||h.includes('apuesta')&&h.includes('partido')||h.includes('pronostico');});}
function closestCard(el){let p=el;for(let i=0;i<6&&p;i++,p=p.parentElement){if(/card|stat|kpi|box/.test((p.className||'').toString()))return p}return el.parentElement}
function paintHome(){for(const e of [...document.querySelectorAll('body *')].filter(e=>e.children.length===0&&visible(e))){const t=norm(e.textContent);if(t==='pendientes de apostar'||t.includes('apostados pendientes de resolver')){const c=closestCard(e),v=num(c?.textContent||'');if(c)c.classList.toggle('af-red',v>0)}if(t==='beneficio'||t==='roi'||t.includes('beneficio total')||t.includes('roi total')){const c=closestCard(e);if(!c)continue;const v=num(c.textContent.replace(e.textContent,''));c.classList.remove('af-green','af-red');if(v>0)c.classList.add('af-green');if(v<0)c.classList.add('af-red')}}}
function exportTable(table,type,name){if(!table)return toast('No hay datos para exportar');const clone=table.cloneNode(true);clone.querySelectorAll('.af-actions,button,input').forEach(x=>x.remove());if(type==='excel'){const html=`<html><head><meta charset="utf-8"></head><body>${clone.outerHTML}</body></html>`,blob=new Blob([html],{type:'application/vnd.ms-excel'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.xls';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}else{const w=window.open('','_blank');w.document.write(`<html><head><title>${name}</title><style>body{font-family:Arial;padding:20px}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #ccc;padding:5px}</style></head><body><h1>${name}</h1>${clone.outerHTML}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}}
function enhanceResolved(){const table=resolvedTable();if(!table)return;const host=table.parentElement;if(!host.querySelector('.af-exportbar')){const bar=document.createElement('div');bar.className='af-toolbar af-exportbar';bar.innerHTML='<button class="af-btn" data-af="xlsx">Exportar Excel</button><button class="af-btn secondary" data-af="pdf">Exportar PDF</button><span class="af-note">Desactivar excluye el pick de las estadísticas sin borrarlo.</span>';host.insertBefore(bar,table);bar.querySelector('[data-af=xlsx]').onclick=()=>exportTable(table,'excel','pronosticos-resueltos');bar.querySelector('[data-af=pdf]').onclick=()=>exportTable(table,'pdf','pronosticos-resueltos')}
const rows=[...table.querySelectorAll('tbody tr')];for(const r of rows){const raw=[...r.cells].filter(c=>!c.classList.contains('af-actions-cell')).map(c=>c.textContent).join('|'),id=hash(norm(raw));if(state.deletedResolved[id]){r.style.display='none';continue}r.classList.toggle('af-muted',!!state.disabledResolved[id]);let cell=r.querySelector('.af-actions-cell');if(!cell){cell=document.createElement('td');cell.className='af-actions-cell';r.appendChild(cell)}cell.innerHTML='';const wrap=document.createElement('div');wrap.className='af-actions';const toggle=document.createElement('button');toggle.className='af-btn secondary';toggle.textContent=state.disabledResolved[id]?'Activar':'Desactivar';toggle.onclick=()=>{state.disabledResolved[id]=!state.disabledResolved[id];save();enhanceResolved();window.appFutbolVerifyAssociations?.();toast(state.disabledResolved[id]?'Pronóstico desactivado':'Pronóstico activado')};const del=document.createElement('button');del.className='af-btn danger';del.textContent='Eliminar';del.onclick=()=>{if(confirm('¿Eliminar definitivamente este pronóstico resuelto?')){state.deletedResolved[id]=true;save();r.style.display='none';window.appFutbolVerifyAssociations?.();toast('Pronóstico eliminado')}};wrap.append(toggle,del);cell.appendChild(wrap)}
if(table.tHead?.rows[0]&&!table.tHead.rows[0].querySelector('.af-actions-head')){const th=document.createElement('th');th.className='af-actions-head';th.textContent='Gestión';table.tHead.rows[0].appendChild(th)}}
function enhanceLineSort(){for(const table of [...document.querySelectorAll('table')].filter(visible)){const hs=tableHeaders(table),li=hs.findIndex(h=>h.includes('linea')),hi=hs.findIndex(h=>h.includes('acierto')||h==='%'||h.includes('% actual')),ri=hs.findIndex(h=>h.includes('roi')),pi=hs.findIndex(h=>h.includes('beneficio'));if(li<0||(hi<0&&ri<0&&pi<0))continue;[[hi,'hit'],[ri,'roi'],[pi,'profit']].forEach(([idx,f])=>{if(idx<0||!table.tHead?.rows[0]?.cells[idx])return;const th=table.tHead.rows[0].cells[idx];th.classList.add('af-sort');if(!th.dataset.afSort){th.dataset.afSort='1';th.onclick=()=>sortTable(table,f)}});sortTable(table,state.sort.field||'roi',state.sort.dir||'desc',true)}}
function sortTable(table,field,dir,initial){const hs=tableHeaders(table),idx=field==='roi'?hs.findIndex(h=>h.includes('roi')):field==='hit'?hs.findIndex(h=>h.includes('acierto')||h.includes('%')):hs.findIndex(h=>h.includes('beneficio'));if(idx<0||!table.tBodies[0])return;if(!initial){if(state.sort.field===field)state.sort.dir=state.sort.dir==='desc'?'asc':'desc';else{state.sort.field=field;state.sort.dir='desc'}save()}else if(dir){state.sort.field=field;state.sort.dir=dir}const rows=[...table.tBodies[0].rows].sort((a,b)=>{const av=num(a.cells[idx]?.textContent),bv=num(b.cells[idx]?.textContent);return state.sort.dir==='asc'?av-bv:bv-av});rows.forEach(r=>table.tBodies[0].appendChild(r))}
async function executeAnalysis(){const before=alertTables().reduce((n,t)=>n+t.querySelectorAll('tbody tr').length,0);let fired=0;
const btns=[...document.querySelectorAll('button,[role="button"]')].filter(e=>visible(e)&&!/ejecutar ahora/.test(norm(e.textContent))&&/(analiz|buscar pronost|revisar partido|actualizar pronost|detectar)/.test(norm(e.textContent)));for(const b of btns.slice(0,3)){try{b.click();fired++}catch{}}
if(!fired){const names=Object.getOwnPropertyNames(window).filter(k=>/(analiz|scan|detect|search|buscar|pronost|automat)/i.test(k));for(const k of names){try{const fn=window[k];if(typeof fn==='function'&&fn.length===0&&!/print|alert|confirm|prompt/i.test(k)){const v=fn();if(v&&typeof v.then==='function')await v;fired++;if(fired>=3)break}}catch{}}}
await new Promise(r=>setTimeout(r,1200));window.appFutbolVerifyAssociations?.();const after=alertTables().reduce((n,t)=>n+t.querySelectorAll('tbody tr').length,0),diff=Math.max(0,after-before);if(diff>0)toast(`Se han encontrado ${diff} pronóstico${diff===1?'':'s'} nuevo${diff===1?'':'s'}. Revisa Avisos.`);else if(fired)toast('Análisis ejecutado: no se han encontrado nuevos pronósticos.');else toast('No existe un motor de análisis ejecutable conectado a esta versión de la app.');}
function enhanceAutomations(){const anchors=[...document.querySelectorAll('h1,h2,h3,[role="tab"],button,a')].filter(e=>visible(e)&&norm(e.textContent).includes('automatiz'));if(!anchors.length)return;let sec=anchors[0];for(let i=0;i<5&&sec.parentElement;i++){sec=sec.parentElement;if(sec.querySelector('button,input,table'))break}if(sec.querySelector('[data-af-run-now]'))return;const b=document.createElement('button');b.className='af-btn';b.dataset.afRunNow='1';b.textContent='Ejecutar ahora';b.onclick=executeAnalysis;sec.insertBefore(b,sec.firstChild)}
function enhanceSettings(){const candidates=[...document.querySelectorAll('h1,h2,h3,[role="tab"],button,a')].filter(e=>visible(e)&&/(ajustes|configuracion)/.test(norm(e.textContent)));if(!candidates.length)return;let sec=candidates[0];for(let i=0;i<5&&sec.parentElement;i++){sec=sec.parentElement;if(sec.querySelector('button,input'))break}[...sec.querySelectorAll('button')].filter(b=>norm(b.textContent).includes('restablecer datos prueba')).forEach(b=>b.remove());if(sec.querySelector('[data-af-bookmakers]'))return;const box=document.createElement('div');box.dataset.afBookmakers='1';box.style.margin='16px 0';box.innerHTML='<h3>Casas de apuestas</h3><div class="af-toolbar"><input data-af-bookmaker-input placeholder="Nueva casa de apuestas" style="padding:9px;border:1px solid #ccc;border-radius:8px"><button class="af-btn" data-af-add-bookmaker>Añadir</button></div><div data-af-bookmaker-list></div>';sec.appendChild(box);const render=()=>{const l=box.querySelector('[data-af-bookmaker-list]');l.innerHTML='';state.bookmakers.forEach((x,i)=>{const s=document.createElement('span');s.className='af-badge';s.textContent=x+' ×';s.style.cursor='pointer';s.onclick=()=>{state.bookmakers.splice(i,1);save();render()};l.appendChild(s)})};box.querySelector('[data-af-add-bookmaker]').onclick=()=>{const inp=box.querySelector('[data-af-bookmaker-input]'),v=inp.value.trim();if(v&&!state.bookmakers.includes(v)){state.bookmakers.push(v);save();inp.value='';render()}};render()}
function run(){paintHome();enhanceResolved();enhanceLineSort();enhanceAutomations();enhanceSettings()}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(run,180)}).observe(document.documentElement,{subtree:true,childList:true,characterData:true});document.addEventListener('click',()=>setTimeout(run,220),true);setTimeout(run,500);setTimeout(run,1800);window.appFutbolRunNow=executeAnalysis;
})();