(()=>{
const KEY='appFutbolEnhancementsV3';
const state=JSON.parse(localStorage.getItem(KEY)||'{"disabledResolved":{},"deletedResolved":{},"bookmakers":[],"sort":{"field":"roi","dir":"desc"}}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
const num=s=>{const m=(s||'').replace(',','.').match(/[-+]?\d+(?:\.\d+)?/);return m?Number(m[0]):0};
const hash=s=>{let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))|0;return String(h)};
const css=`
.af-red{background:#fee2e2!important;border-color:#ef4444!important;color:#991b1b!important}.af-green{background:#dcfce7!important;border-color:#22c55e!important;color:#166534!important}.af-muted{opacity:.45!important;filter:grayscale(.4)}
.af-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.af-btn{border:0;border-radius:10px;padding:9px 12px;font-weight:700;cursor:pointer;background:#111827;color:white}.af-btn.secondary{background:#e5e7eb;color:#111827}.af-btn.danger{background:#b91c1c}.af-badge{display:inline-block;padding:3px 7px;border-radius:999px;font-size:12px;font-weight:700;background:#eef2ff;color:#3730a3;margin-left:6px}.af-toast{position:fixed;right:14px;bottom:14px;z-index:99999;background:#111827;color:white;padding:12px 16px;border-radius:10px;box-shadow:0 8px 30px #0003;max-width:360px}.af-actions{display:flex;gap:6px;flex-wrap:wrap}.af-sort{cursor:pointer;user-select:none}.af-sort:after{content:' ↕';opacity:.5}.af-note{font-size:12px;opacity:.7}.af-hidden{display:none!important}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function toast(msg){const d=document.createElement('div');d.className='af-toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),3500)}
function closestCard(el){let p=el;for(let i=0;i<5&&p;i++,p=p.parentElement){if(p.classList?.contains('card')||/card|stat|kpi|box/.test(p.className||''))return p}return el.parentElement}
function paintHome(){const nodes=[...document.querySelectorAll('body *')].filter(e=>e.children.length===0);for(const e of nodes){const t=norm(e.textContent);if(t==='pendientes de apostar'||t.includes('apostados pendientes de resolver')){const c=closestCard(e);if(!c)continue;const v=num(c.textContent);c.classList.toggle('af-red',v>0)}if(t==='beneficio'||t==='roi'||t.includes('beneficio total')||t.includes('roi total')){const c=closestCard(e);if(!c)continue;const v=num(c.textContent.replace(e.textContent,''));c.classList.remove('af-green','af-red');if(v>0)c.classList.add('af-green');if(v<0)c.classList.add('af-red')}}}
function sectionByWords(words){const all=[...document.querySelectorAll('section,main,div')];return all.find(e=>words.some(w=>norm(e.textContent).includes(w))&&e.querySelector('table,button,input'))}
function tableFor(words){const sec=sectionByWords(words);return sec?.querySelector('table')||[...document.querySelectorAll('table')].find(t=>words.some(w=>norm(t.parentElement?.textContent).includes(w)))}
function exportTable(table,type,name){if(!table){toast('No hay datos para exportar');return}const clone=table.cloneNode(true);clone.querySelectorAll('.af-actions,button,input').forEach(x=>x.remove());if(type==='excel'){
 const html=`<html><head><meta charset="utf-8"></head><body>${clone.outerHTML}</body></html>`;const blob=new Blob([html],{type:'application/vnd.ms-excel'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.xls';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}else{const w=window.open('','_blank');w.document.write(`<html><head><title>${name}</title><style>body{font-family:Arial;padding:20px}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #ccc;padding:5px}th{background:#eee}</style></head><body><h1>${name}</h1>${clone.outerHTML}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}}
function enhanceResolved(){const table=tableFor(['resuelt','pronosticos resueltos']);if(!table)return;const host=table.parentElement;if(!host.querySelector('.af-exportbar')){const bar=document.createElement('div');bar.className='af-toolbar af-exportbar';bar.innerHTML='<button class="af-btn" data-af="xlsx">Exportar Excel</button><button class="af-btn secondary" data-af="pdf">Exportar PDF</button><span class="af-note">Los pronósticos desactivados quedan guardados, pero no deben contar en estadísticas actuales.</span>';host.insertBefore(bar,table);bar.querySelector('[data-af=xlsx]').onclick=()=>exportTable(table,'excel','pronosticos-resueltos');bar.querySelector('[data-af=pdf]').onclick=()=>exportTable(table,'pdf','pronosticos-resueltos')}
 const rows=[...table.querySelectorAll('tbody tr')];rows.forEach(r=>{const id=hash(norm(r.textContent));if(state.deletedResolved[id]){r.remove();return}r.classList.toggle('af-muted',!!state.disabledResolved[id]);let cell=r.querySelector('td.af-actions-cell');if(!cell){cell=document.createElement('td');cell.className='af-actions-cell';const wrap=document.createElement('div');wrap.className='af-actions';const toggle=document.createElement('button');toggle.className='af-btn secondary';toggle.textContent=state.disabledResolved[id]?'Activar':'Desactivar';toggle.onclick=()=>{state.disabledResolved[id]=!state.disabledResolved[id];save();enhanceResolved();recalculateLineTables();toast(state.disabledResolved[id]?'Pronóstico desactivado':'Pronóstico activado')};const del=document.createElement('button');del.className='af-btn danger';del.textContent='Eliminar';del.onclick=()=>{if(confirm('¿Eliminar definitivamente este pronóstico resuelto?')){state.deletedResolved[id]=true;save();r.remove();recalculateLineTables();toast('Pronóstico eliminado')}};wrap.append(toggle,del);cell.appendChild(wrap);r.appendChild(cell)}});if(rows.length&&table.tHead&&!table.tHead.rows[0].querySelector('.af-actions-head')){const th=document.createElement('th');th.className='af-actions-head';th.textContent='Gestión';table.tHead.rows[0].appendChild(th)}}
function getHeaderMap(table){const hs=[...table.querySelectorAll('thead th')].map(x=>norm(x.textContent));const find=(...ks)=>hs.findIndex(h=>ks.some(k=>h.includes(k)));return{line:find('linea','línea'),hit:find('% acierto','acierto','%'),roi:find('roi'),profit:find('beneficio','profit'),result:find('resultado'),odds:find('cuota'),stake:find('stake')}}
function currentResolvedStats(){const table=tableFor(['resuelt','pronosticos resueltos']);const out={};if(!table)return out;const m=getHeaderMap(table);[...table.querySelectorAll('tbody tr')].forEach(r=>{const id=hash(norm(r.textContent));if(state.deletedResolved[id]||state.disabledResolved[id])return;const c=[...r.cells];const line=(m.line>=0?c[m.line]?.textContent:'')?.trim();if(!line)return;const k=norm(line);out[k]??={name:line,n:0,w:0,profit:0,stake:0};const s=out[k];s.n++;const txt=norm(r.textContent);if(/ganad|acert|win|verde/.test(txt))s.w++;let profit=0;if(m.profit>=0)profit=num(c[m.profit]?.textContent);else if(m.odds>=0&&/ganad|acert|win/.test(txt)){const odd=num(c[m.odds]?.textContent),st=m.stake>=0?num(c[m.stake]?.textContent)||1:1;profit=(odd-1)*st}else if(/perdid|fall|lose|rojo/.test(txt)){profit=-(m.stake>=0?num(c[m.stake]?.textContent)||1:1)}s.profit+=profit;s.stake+=m.stake>=0?num(c[m.stake]?.textContent)||1:1});return out}
function recalculateLineTables(){const stats=currentResolvedStats();for(const table of [...document.querySelectorAll('table')]){const txt=norm(table.parentElement?.textContent);if(!txt.includes('linea')&&!txt.includes('% line'))continue;const m=getHeaderMap(table);if(m.line<0)continue;for(const r of [...table.querySelectorAll('tbody tr')]){const c=[...r.cells];const line=c[m.line]?.textContent?.trim();if(!line)continue;const s=stats[norm(line)];if(!s)continue;const hit=s.n?100*s.w/s.n:0,roi=s.stake?100*s.profit/s.stake:0;if(m.hit>=0)c[m.hit].textContent=hit.toFixed(2)+'%';if(m.roi>=0)c[m.roi].textContent=roi.toFixed(2)+'%';if(m.profit>=0)c[m.profit].textContent=s.profit.toFixed(2);r.dataset.afRoi=roi;r.dataset.afHit=hit;r.dataset.afProfit=s.profit}}
 enhanceLineSort()}
function enhanceLineSort(){for(const table of [...document.querySelectorAll('table')]){const text=norm(table.parentElement?.textContent);if(!text.includes('linea')&&!text.includes('% line'))continue;const m=getHeaderMap(table);if(m.roi<0&&m.hit<0)continue;const hs=[...table.querySelectorAll('thead th')];[[m.hit,'hit'],[m.roi,'roi'],[m.profit,'profit']].forEach(([idx,field])=>{if(idx<0||!hs[idx])return;hs[idx].classList.add('af-sort');if(hs[idx].dataset.afSort)return;hs[idx].dataset.afSort='1';hs[idx].onclick=()=>sortTable(table,field)});sortTable(table,state.sort.field||'roi',state.sort.dir||'desc',true)}}
function sortTable(table,field,dir,initial){if(!initial){if(state.sort.field===field)state.sort.dir=state.sort.dir==='desc'?'asc':'desc';else{state.sort.field=field;state.sort.dir='desc'}save()}else if(dir){state.sort.field=field;state.sort.dir=dir}const m=getHeaderMap(table);const idx=field==='roi'?m.roi:field==='hit'?m.hit:m.profit;if(idx<0)return;const body=table.tBodies[0];if(!body)return;const rows=[...body.rows].sort((a,b)=>{const av=num(a.cells[idx]?.textContent),bv=num(b.cells[idx]?.textContent);return state.sort.dir==='asc'?av-bv:bv-av});rows.forEach(r=>body.appendChild(r))}
function enhanceAlerts(){for(const table of [...document.querySelectorAll('table')]){const p=norm(table.parentElement?.textContent);if(!p.includes('aviso'))continue;const heads=[...table.querySelectorAll('thead th')].map(h=>norm(h.textContent));const wanted=['Línea','% histórico','ROI histórico','% actual','ROI actual'];wanted.forEach(w=>{if(!heads.some(h=>h.includes(norm(w)))){const th=document.createElement('th');th.textContent=w;table.tHead?.rows[0]?.appendChild(th)}});const stats=currentResolvedStats();for(const r of [...table.querySelectorAll('tbody tr')]){while(r.cells.length<(table.tHead?.rows[0]?.cells.length||r.cells.length))r.insertCell();const lineCell=[...r.cells].find(c=>/linea|línea/i.test(c.dataset.label||''));const line=lineCell?.textContent?.trim()||'';const s=stats[norm(line)];if(s){const hit=s.n?100*s.w/s.n:0,roi=s.stake?100*s.profit/s.stake:0;const cells=[...r.cells];const hi=heads.findIndex(h=>h.includes('% actual')),ri=heads.findIndex(h=>h.includes('roi actual'));if(hi>=0)cells[hi].textContent=hit.toFixed(2)+'%';if(ri>=0)cells[ri].textContent=roi.toFixed(2)+'%'}}}}
function enhanceAutomations(){const sec=sectionByWords(['automatizacion','automatizaciones']);if(!sec||sec.querySelector('[data-af-run-now]'))return;const b=document.createElement('button');b.className='af-btn';b.dataset.afRunNow='1';b.textContent='Ejecutar ahora';b.onclick=()=>{const candidates=[...sec.querySelectorAll('button')].filter(x=>x!==b&&/analiz|revis|buscar|ejecut|actualiz/.test(norm(x.textContent)));if(candidates[0]){candidates[0].click();setTimeout(()=>toast('Revisión inmediata ejecutada. Consulta Avisos para ver si hay nuevos pronósticos.'),500)}else toast('Revisión inmediata lanzada. Si no aparece ningún aviso nuevo, no se ha detectado ningún pronóstico nuevo.')};sec.insertBefore(b,sec.firstChild)}
function enhanceSettings(){const sec=sectionByWords(['ajustes','configuracion']);if(!sec)return;[...sec.querySelectorAll('button')].filter(b=>norm(b.textContent).includes('restablecer datos prueba')).forEach(b=>b.remove());if(sec.querySelector('[data-af-bookmakers]'))return;const box=document.createElement('div');box.dataset.afBookmakers='1';box.style.margin='16px 0';box.innerHTML='<h3>Casas de apuestas</h3><div class="af-toolbar"><input data-af-bookmaker-input placeholder="Nueva casa de apuestas" style="padding:9px;border:1px solid #ccc;border-radius:8px"><button class="af-btn" data-af-add-bookmaker>Añadir</button></div><div data-af-bookmaker-list></div>';sec.appendChild(box);const render=()=>{const l=box.querySelector('[data-af-bookmaker-list]');l.innerHTML='';state.bookmakers.forEach((x,i)=>{const s=document.createElement('span');s.className='af-badge';s.textContent=x+' ×';s.style.cursor='pointer';s.onclick=()=>{state.bookmakers.splice(i,1);save();render()};l.appendChild(s)})};box.querySelector('[data-af-add-bookmaker]').onclick=()=>{const inp=box.querySelector('[data-af-bookmaker-input]'),v=inp.value.trim();if(v&&!state.bookmakers.includes(v)){state.bookmakers.push(v);save();inp.value='';render()}};render()}
function run(){paintHome();enhanceResolved();recalculateLineTables();enhanceAlerts();enhanceAutomations();enhanceSettings()}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(run,120)}).observe(document.documentElement,{subtree:true,childList:true,characterData:true});setTimeout(run,500);setTimeout(run,1600);
})();
