(()=>{
'use strict';
const norm=s=>(s??'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
const n=v=>{const m=String(v??'').replace(',','.').match(/[-+]?\d+(?:\.\d+)?/);return m?Number(m[0]):null};
const hs=t=>[...t.querySelectorAll('thead th')].map(x=>norm(x.textContent));
const style=document.createElement('style');style.textContent='.afv-pos{background:#dcfce7!important;color:#166534!important;font-weight:700}.afv-neg{background:#fee2e2!important;color:#991b1b!important;font-weight:700}';document.head.appendChild(style);
function color(){for(const t of document.querySelectorAll('table')){const h=hs(t),ri=h.findIndex(x=>x.includes('roi')),bi=h.findIndex(x=>x.includes('beneficio')||x.includes('profit'));if(ri<0&&bi<0)continue;for(const r of t.querySelectorAll('tbody tr'))for(const i of [ri,bi])if(i>=0&&r.cells[i]){const v=n(r.cells[i].textContent);r.cells[i].classList.remove('afv-pos','afv-neg');if(v>0)r.cells[i].classList.add('afv-pos');if(v<0)r.cells[i].classList.add('afv-neg')}}}
function resolvedRows(){const out=[];for(const t of document.querySelectorAll('table')){const h=hs(t),pi=h.findIndex(x=>x.includes('partido')),li=h.findIndex(x=>x==='linea(s)'||x==='linea'||x==='línea'||x.includes('linea')),ai=h.findIndex(x=>x==='a/f'||x.includes('acierto')||x.includes('estado')),bi=h.findIndex(x=>x.includes('beneficio')),si=h.findIndex(x=>x.includes('stake')),oi=h.findIndex(x=>x.includes('cuota apostada')||x==='cuota');if(pi<0||li<0)continue;for(const r of t.querySelectorAll('tbody tr')){const p=norm(r.cells[pi]?.textContent);if(p.includes('como')&&p.includes('leipzig')){if(/manual|sin linea/.test(norm(r.cells[li]?.textContent)))r.cells[li].textContent='Favorito local Champions 1,70–1,84';}const line=r.cells[li]?.textContent.trim();if(!line||/manual|sin linea/.test(norm(line)))continue;const txt=norm(r.textContent);let win=null;if(/acierto|ganad|\bwin\b/.test(txt))win=true;else if(/fallo|perdid|\bloss\b/.test(txt))win=false;const stake=si>=0?n(r.cells[si]?.textContent):1;const benefit=bi>=0?n(r.cells[bi]?.textContent):null;const odds=oi>=0?n(r.cells[oi]?.textContent):null;out.push({line,win,stake:stake??1,benefit:benefit??(win===true&&odds!=null?(odds-1)*(stake??1):win===false?-(stake??1):null)});}}return out}
function stats(){const rows=resolvedRows(),map=new Map();for(const x of rows){const k=norm(x.line),s=map.get(k)||{line:x.line,n:0,w:0,stake:0,benefit:0};if(x.win!==null){s.n++;if(x.win)s.w++}s.stake+=x.stake||0;s.benefit+=x.benefit||0;map.set(k,s)}
for(const t of document.querySelectorAll('table')){const h=hs(t),li=h.findIndex(x=>x==='linea'||x==='línea'||x.includes('linea')),hi=h.findIndex(x=>x.includes('%')||x.includes('acierto')),ri=h.findIndex(x=>x.includes('roi')),bi=h.findIndex(x=>x.includes('beneficio'));if(li<0||(hi<0&&ri<0&&bi<0))continue;for(const r of t.querySelectorAll('tbody tr')){let name=r.cells[li]?.textContent.trim()||'';if(/manual|sin linea/.test(norm(name))&&norm(r.textContent).includes('como')){name='Favorito local Champions 1,70–1,84';r.cells[li].textContent=name}const s=map.get(norm(name));if(!s)continue;if(hi>=0)r.cells[hi].textContent=s.n?(100*s.w/s.n).toFixed(2)+'%':'—';if(ri>=0)r.cells[ri].textContent=s.stake?(100*s.benefit/s.stake).toFixed(2)+'%':'—';if(bi>=0)r.cells[bi].textContent=(s.benefit>=0?'+':'')+s.benefit.toFixed(2)+'u';}}
color()}
function run(){stats();color()}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(run,100)}).observe(document.documentElement,{subtree:true,childList:true,characterData:true});document.addEventListener('click',()=>setTimeout(run,180),true);setTimeout(run,400);setTimeout(run,1200);window.appFutbolSyncStats=run;
})();